name: Checks

on:
  workflow_call:
  pull_request:
    paths-ignore: ['README.md', 'LICENSE', '.editorconfig']
    branches: [main, develop, staging]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Install dependencies
        uses: ./.github/actions/pnpm-install
      - name: Lint and format
        run: pnpm check
      - name: Build
        run: pnpm build
      - name: Check types
        run: pnpm check:types
      - name: Check spec types
        run: pnpm check:types:spec
      - name: Check circular dependencies
        run: pnpm check:circular-deps
      - name: Knip
        run: pnpm knip:check
      - name: Test
        run: pnpm -r --workspace-concurrency=1 --filter './packages/**' test
